// 标记类型常量
export const MARKER_ARROW = 0;
export const MARKER_CUBE = 1;
export const MARKER_SPHERE = 2;
export const MARKER_CYLINDER = 3;
export const MARKER_LINE_STRIP = 4;
export const MARKER_LINE_LIST = 5;
export const MARKER_CUBE_LIST = 6;
export const MARKER_SPHERE_LIST = 7;
export const MARKER_POINTS = 8;
export const MARKER_TEXT_VIEW_FACING = 9;
export const MARKER_MESH_RESOURCE = 10;
export const MARKER_TRIANGLE_LIST = 11;

// 交互式标记反馈类型
export const INTERACTIVE_MARKER_KEEP_ALIVE = 0;
export const INTERACTIVE_MARKER_POSE_UPDATE = 1;
export const INTERACTIVE_MARKER_MENU_SELECT = 2;
export const INTERACTIVE_MARKER_BUTTON_CLICK = 3;
export const INTERACTIVE_MARKER_MOUSE_DOWN = 4;
export const INTERACTIVE_MARKER_MOUSE_UP = 5;

// 交互式标记控制类型
export const INTERACTIVE_MARKER_NONE = 0;
export const INTERACTIVE_MARKER_MENU = 1;
export const INTERACTIVE_MARKER_BUTTON = 2;
export const INTERACTIVE_MARKER_MOVE_AXIS = 3;
export const INTERACTIVE_MARKER_MOVE_PLANE = 4;
export const INTERACTIVE_MARKER_ROTATE_AXIS = 5;
export const INTERACTIVE_MARKER_MOVE_ROTATE = 6;
export const INTERACTIVE_MARKER_MOVE_3D = 7;
export const INTERACTIVE_MARKER_ROTATE_3D = 8;
export const INTERACTIVE_MARKER_MOVE_ROTATE_3D = 9;

// 交互式标记旋转行为
export const INTERACTIVE_MARKER_INHERIT = 0;
export const INTERACTIVE_MARKER_FIXED = 1;
export const INTERACTIVE_MARKER_VIEW_FACING = 2;